config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  

  root 'welcome#index'
  get "all_locations" => "locations#index"

  resources :comments

  resources :locations
  resources :cohorts
  resources :assignments 
  resources :submissions     
  
  
  

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
	belongs_to :cohort
	belongs_to :user
	has_many :submissions
	accepts_nested_attributes_for :submissions
	has_many :comments, :as => :commentable
	accepts_nested_attributes_for :comments
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # before_filter :load
  respond_to :html, :json, :js

 
  # load_and_authorize_resource 

  # def load
  #   @assignments = Assignment.all
  #   @assignment = Assignment.new
  # end

  def index
  end

  def show

    @assignment = Assignment.find(params[:id])
    @new_comment = @assignment.comments.build

    # @assignment = Assignment.find(params[:id])
    @submission = @assignment.submissions.build
    # @new_comment = @assignment.comments.build
    # user = @submission.assignment_id = current_user.id
  end




  def create
    @assignment = Assignment.new(assignment_params)
    @assignment.user_id = current_user.id
    if @assignment.save
      redirect_to :back
      flash[:notice] = "Successfully created post."
      @assignments = Assignment.all
    end
  end

  def edit
    @assignment = Assignment.find(params[:id])
    # unauthorized! if cannot? :edit, @article
  end

  def update
    @assignment = Assignment.find(params[:id])
    if @assignment.update_attributes(assignment_params)
      flash[:notice] = "Successfully updated post."
      respond_with @assignment
    end
  end


  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy
    redirect_to :back
    flash[:notice] = "Successfully destroyed post."
    @assignments = Assignment.all
  end

  def change_completed
    @assignment = Assignment.find(params[:id])
    if @assignment.completed
      val = false
    else
      val = true
    end
    @assignment.update_attributes(:completed => val)
    redirect_to assignments_path
  end

  private

  def assignment_params
    params.require(:assignment).permit!
  end 

end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_assignments.html.haml
- @assignments.each do |assignment|
	= link_to assignment.title, assignments
	%br
	= assignment.description
	%br
	= assignment.due_date
	%br
	= link_to "Edit", edit_assignment_path(assignment),:remote => true
	%br
	= link_to "Remove", assignment, :remote => true, :confirm => 'Are you sure?', :method => :delete
	%br
	%br

- @assignments.each do |assignment|
	= assignment.title
	= assignment.description
	= assignment.due_date
	- if can? :update, @assignment
		= link_to "Edit", edit_assignment_path(assignment),:remote => true
	- else 
		%h4 Edit
	- if can? :delete, @assignment
		= link_to "Remove", assignment, :remote => true, :confirm => 'Are you sure?', :method => :delete
	- else 
		%h4 Delete

app/views/assignments/_form.html.haml
%h1 HELLO

= form_for @assignment, :remote => true do |assignment|
		= assignment.hidden_field :cohort_id
		= assignment.hidden_field :user_id
		%br
		= assignment.label :title
		%br
		= assignment.text_field :title
		%br
		= assignment.label :description
		%br
		= assignment.text_field :description
		%br
		= assignment.label :duedate
		%br
		= assignment.text_field :due_date
		%br
		= assignment.submit "Create New", :method => "POST"

app/views/assignments/create.js.erb
// $(":input:not(input[type=submit])").val("");
// $("#assignments_list").html("<%= escape_javascript( render(:partial => "assignments") ) %>");

app/views/assignments/destroy.js.erb
// $("#assignments_list").html("<%= escape_javascript( render(:partial => "assignments") ) %>");

app/views/assignments/edit.js.erb
// $("#assignment_form").html("<%= escape_javascript( render(:partial => "form") ) %>");

app/views/assignments/index.html.haml
/ %h1 Hi the main page that will display all the assignments

/ = link_to "Go to All Assignments for this Cohort", all_locations_path

/ #assignments_list= render :partial => "assignments"

/ #assignment_form= render :partial => "form"

app/views/assignments/show.html.haml
%h4 Assignments for #{@assignment.title}


.row
  .col-sm-12.col-lg-12
    %h4
      %strong Submissions
    %table.display
      %thead
        %tr
          %th.center User
          %th Github Link
          %th Go to Github
          %th Finished?
          %th View Work
          %th Delete
      %tbody
      - @assignment.submissions.includes(:user).each do |submission|
        %tr.odd
          %td= image_tag submission.user.photo_pic.url,:style => "border-radius: 50%; height:50px; width:50px"
          - if can? :manage, submission
            %td= best_in_place submission, :github_link, :type => :input
            %td= link_to submission.github_link, url_for(submission.github_link)
          - else
            %td= submission.github_link
          - if can? :manage, submission
            %td= best_in_place submission, :finished, :type => :input
          - else
            %td= submission.finished
          %td= link_to "View Assignment", submission
          - if can? :manage, submission
            %td.center= link_to "Delete", submission, :confirm => 'Are you sure?', :method => :delete, :onSubmit => "window.location.href=window.location.href"
          - else
            %td Delete

/ = link_to "View Assignment", submission

= form_for @submission do |submission|
  = submission.hidden_field :assignment_id
  = submission.hidden_field :assignment_id
  %br
  = submission.label :Submit_Your_Homework
  %br
  = submission.text_field :title
  %br
  = submission.submit "Create New", :method => "POST", :onSubmit => "window.location.href=window.location.href"



%br
%br
.col-xs-1.col-sm-12
  .panel.panel-default
    .panel-body
      %p.lead
      %br
      %br
      - @assignment.comments.includes(:user).each do |t|
        = image_tag t.user.photo_pic.url,:style => "border-radius: 50%; height:50px; width:50px"
        = best_in_place t, :message, :type => :input
        %br
        %br


      .container{:style => "float:center;"}
        = form_for @new_comment do |f|
          = f.hidden_field :commentable_id, value: @new_comment.commentable_id
          = f.hidden_field :commentable_type, value: @new_comment.commentable_type
          = f.hidden_field :user_id, value: current_user.id
          = f.text_field :message
          = f.submit "Comment!"
      %br



/ %br
/ %br
/ .col-xs-1.col-sm-12
/   .panel.panel-default
/     .panel-body
/       %p.lead
/       %br
/       %br
/       - @assignment.comments.includes(:user).each do |comment|
/         = image_tag comment.user.photo_pic.url,:style => "border-radius: 50%; height:50px; width:50px" 
/         = best_in_place comment, :message, :type => :input
/         %br
/         %br


/       .container{:style => "float:center;"}
/         = form_for @new_comment do |f|
/           = f.hidden_field :commentable_id, value: @new_comment.commentable_id
/           = f.hidden_field :commentable_type, value: @new_comment.commentable_type
/           = f.text_field :message
/           = f.submit "Comment!"
/       %br



/ %h4 Assignments for #{@assignment.title}

/ .row
/   .col-sm-12.col-lg-12
/     %h4
/       %strong Locations
/     %table.display
/       %thead
/         %tr
/           %th.center User
/           %th Description
/           %th Due_date
/           %th Link Icon
/           %th Remove
/           %th Maybe Student Count
/       %tbody
/       - @assignment.submissions.includes(:user).each do |submission|
/         %tr.odd
/           %td= image_tag submission.user.photo_pic.url,:style => "border-radius: 50%; height:50px; width:50px"
/           - if can? :manage, submission
/             %td= best_in_place submission, :title, :type => :input
/           - else
/             %td= submission.title
/           - if can? :manage, submission
/             %td= best_in_place submission, :title, :type => :input
/           - else
/             %td= submission.title
/           - if can? :manage, submission
/             %td= best_in_place submission, :title, :type => :input
/           - else
/             %td= submission.title
/           - if user.submission.title
/             %td= link_to submission.title, submission
/           - else
/             = submission.title
/           - if can? :manage, submission
/             %td.center= link_to "Delete", submission, :remote => true, :confirm => 'Are you sure?', :method => :delete
/           - else
/           %td Delete
/ = @assignment.submissions.users.photo_pic

/ - @assignment.submissions.each do |submission|
/ 	= best_in_place submission, :title, :type => :input
/ 	%br
/ 	= link_to submission.title, submission
/ 	%br

/ %h1l nested assignment and submission form

app/views/assignments/update.js.erb
// $("#assignments_list").html("<%= escape_javascript( render(:partial => "assignments") ) %>");