config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  

  root 'welcome#index'
  get "all_locations" => "locations#index"

  resources :comments

  resources :locations
  resources :cohorts
  resources :assignments 
  resources :submissions     
  
  
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :commentable, polymorphic: true
	belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :html, :json

  def index
    @comments = Comments.all

  end

  def new
    @comment = Comments.new
  end



def create
  @new_comment = Comment.new(comment_params)
  @new_comment.user_id = current_user.id # you can do this here OR in your form
  if @new_comment.save
    redirect_to :back
  else
    render assignment_path
  end
end

def download_photo_pic
    @photo = Photo.find(params[:id])
    file = @photo.photo_pic
    send_file file.path
  end

   def update
    @new_comment = Comment.find(params[:id])
    if @new_comment.update_attributes(comment_params)
      flash[:notice] = "Successfully updated post."
      respond_with @new_comment
    end
  end

private

  def comment_params
  params.require(:comment).permit!
  end

end




# class CommentsController < ApplicationController
#   before_filter :load
  
#   def load
#  		@comments = Comment.all
#     @comment = Comment.new
#   end

#   def index
#   end

#   def create
#     @comment = Comment.new(comment_params)
#     if @comment.save
#       flash[:notice] = "Successfully created post."
#       @comments = Comment.all
#     end
#   end

#   def edit
#     @comment = Comment.find(params[:id])
#   end

#   def update
#     @comment = Comment.find(params[:id])
#     if @comment.update_attributes(comment_params)
#       flash[:notice] = "Successfully updated post."
#       @comments = Comment.all
#     end
#   end

#   def destroy
#     @comment = Comment.find(params[:id])
#     @comment.destroy
#     flash[:notice] = "Successfully destroyed post."
#     @comments = Comment.all
#   end

#   private

#   def comment_params
#     params.require(:comment).permit!
#   end 

# end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.haml
- @comments.each do |comment|
		= comment.message
		%br
		= link_to "Edit", edit_comment_path(comment),:remote => true
		= link_to "Remove", comment, :remote => true, :confirm => 'Are you sure?', :method => :delete

app/views/comments/_form.html.haml
= form_for @comment, :remote => true do |comment|
		%br
		= comment.label :message
		%br
		= comment.text_field :message
		%br
		= comment.submit "Create New", :method => "POST"

app/views/comments/create.js.erb
// $(":input:not(input[type=submit])").val("");
// $("#comments_list").html("<%= escape_javascript( render(:partial => "comments") ) %>");

app/views/comments/destroy.js.erb
// $("#comments_list").html("<%= escape_javascript( render(:partial => "comments") ) %>");

app/views/comments/edit.js.erb
// $("#comment_form").html("<%= escape_javascript( render(:partial => "form") ) %>");

app/views/comments/index.html.haml
%h1 Hi the main page that will display all the comments

= link_to "All Comments", comments_path

#comments_list= render :partial => "comments"

#comment_form= render :partial => "form"

app/views/comments/update.js.erb
// $("#comments_list").html("<%= escape_javascript( render(:partial => "comments") ) %>");