config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  

  root 'welcome#index'
  get "all_locations" => "locations#index"

  resources :comments

  resources :locations
  resources :cohorts
  resources :assignments 
  resources :submissions     
  
  
  

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :user
  belongs_to :assignment
  # resourcify
  has_many :comments, :as => :commentable


end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_filter :load
  respond_to :html, :json

  def load
    @submissions = Submission.all
    @submission = Submission.new
  end

  def index
  end

  def show
    @submission = Submission.find(params[:id])
    @new_comment = @submission.comments.build
    # @submission = Submission.find(params[:id])
    # @submission.user_id = current_user.id
  end

  # def create
  #   @submission = Submission.new(submission_params)
  #   @submission.user_id = current_user.id
  #   if @submission.save
  #     flash[:notice] = "Successfully created post."
  #     @submissions = Submission.all
  #   end
  # end

  def create
    @submission = Submission.new(submission_params)
    @submission.user_id = current_user.id
    if @submission.save
      redirect_to :back
    else
      render assignment_path
    end
  end

  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    @submission = Submission.find(params[:id])
    # @submission.user_id = current_user.id
    if @submission.update_attributes(submission_params)
      flash[:notice] = "Successfully updated post."
      respond_with @submission
    end
  end

  def destroy
    @submission = Submission.find(params[:id])
    @submission.destroy
    redirect_to :back
    flash[:notice] = "Successfully destroyed post."
  end

  def change_completed
    @submission = Submission.find(params[:id])
    if @submission.completed
      val = false
    else
      val = true
    end
    @submission.update_attributes(:completed => val)
    redirect_to submissions_path
  end

  private

  def submission_params
    params.require(:submission).permit!
  end 

end

app/views/submissions/_form.html.haml
= form_for @submission, :remote => true do |submission|
		%br
		= submission.label :city
		%br
		= submission.text_field :city
		%p
		= submission.label :state
		%br
		= submission.text_field :state
		%br
		= submission.submit "Create New", :method => "POST"

app/views/submissions/_submissions.html.haml
- @submissions.each do |submission|
	= link_to "Edit", edit_submission_path(submission),:remote => true
	= link_to "Remove", submission, :remote => true, :confirm => 'Are you sure?', :method => :delete

app/views/submissions/create.js.erb
$(":input:not(input[type=submit])").val("");
$("#submissions_list").html("<%= escape_javascript( render(:partial => "submissions") ) %>");

app/views/submissions/destroy.js.erb
$("#submissions_list").html("<%= escape_javascript( render(:partial => "submissions") ) %>");

app/views/submissions/edit.js.erb
$("#submission_form").html("<%= escape_javascript( render(:partial => "form") ) %>");

app/views/submissions/index.html.haml
/ %h1 Hi the main page that will display all the assignments

/ #submissions_list= render :partial => "submissions"

/ #submission_form= render :partial => "form"
/ 	

app/views/submissions/show.html.haml
%br
%br
.col-xs-1.col-sm-12
  .panel.panel-default
    .panel-body
      %p.lead
      = best_in_place @submission, :title, :type => :input
      %br
      %br
      = best_in_place @submission, :all_work, :type => :input 
      %br
      / = best_in_place @submission, :all_work, :type => :textarea, :display_as => :md_submission
      / %br
      / / = @event.description
      / / - @event.comments.each do |t|
      / /   = t.message
      / /   %br
      / /   %br


%br
%br
.col-xs-1.col-sm-12
  .panel.panel-default
    .panel-body
      %p.lead
      %br
      %br
      - @submission.comments.each do |t|
        = best_in_place t, :message, :type => :input
        %br
        %br


      .container{:style => "float:center;"}
        = form_for @new_comment do |f|
          = f.hidden_field :commentable_id, value: @new_comment.commentable_id
          = f.hidden_field :commentable_type, value: @new_comment.commentable_type
          = f.text_field :message
          = f.submit "Comment!"
      %br

app/views/submissions/update.js.erb
// $("#submissions_list").html("<%= escape_javascript( render(:partial => "submissions") ) %>");