config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  

  root 'welcome#index'
  get "all_locations" => "locations#index"

  resources :comments

  resources :locations
  resources :cohorts
  resources :assignments 
  resources :submissions     
  
  
  

end

app/models/location.rb
class Location < ActiveRecord::Base
	has_many :cohorts
	accepts_nested_attributes_for :cohorts
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  respond_to :html, :json, :js
  before_filter :load

  def load
 
    @locations = Location.all
    @location = Location.new
  end

  def index
  end

  def show
    @location = Location.find(params[:id])
    # @cohort = @location.cohorts.build
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to :back
      flash[:notice] = "Successfully created post."
      @locations = Location.all
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    if @location.update_attributes(location_params)
      flash[:notice] = "Successfully updated post."
      respond_with @location
    end
  end

  def destroy
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to :back
    flash[:notice] = "Successfully destroyed post."
    @locations = Location.all
  end

  private

  def location_params
    params.require(:location).permit!
  end 

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.haml
%br
%br

= form_for @location do |location|
	= location.hidden_field :cohort_id
	= location.hidden_field :city
	= location.hidden_field :state
	= location.submit "Hello Admin, Add a New Row and Create a New Location Inline", :method => "POST", :onSubmit => "window.location.href=window.location.href"

%br
%br
%br
%br
%br
%br
%br
%br
%br
%br

app/views/locations/_formtwo.html.haml
%br
%br

= form_for @cohort do |cohort|
	
	= cohort.hidden_field :subject
	= cohort.hidden_field :start_date
	= cohort.hidden_field :end_date
	= cohort.submit "Hello Admin, Add a New Row and Create a New Course Inline", :method => "POST", :onSubmit => "window.location.href=window.location.href"

%br
%br
%br
%br
%br
%br
%br
%br
%br
%br

app/views/locations/_locations.html.haml
.row
  .col-sm-12.col-lg-12
    %h4
      %strong 
    %table.display
      %thead
        %tr
          %th City
          %th State
          %th Link to Cohort
          %th Maybe Student Count
          %th Remove
      %tbody
      - @locations.each do |location|
        %tr.odd
          - if can? :manage, location
            %td= best_in_place location, :city, :type => :input
          - else
            %td= location.city
          - if can? :manage, location
            %td= best_in_place location, :state, :type => :input
          - else
            %td= location.state
          %td= link_to location.city, location
          %td.center Maybe student
          - if can? :manage, location
            %td.center= link_to "Remove L", location, :confirm => 'Are you sure?', :method => :delete, :onSubmit => "window.location.href=window.location.href"
          - else
            %td Edit
          

app/views/locations/_locationstwo.html.haml
.row
  .col-sm-12.col-lg-12
    %h4
      %strong 
    %table.display
      %thead
        %tr
          %th Subject
          %th Teacher
          %th Start_date
          %th End_date
          %th Delete
      %tbody
      - @location.cohorts.each do |cohort|
        %tr.odd
          - if can? :manage, cohort
            %td= best_in_place cohort, :subject, :type => :input
          - else
            %td= cohort.subject
          - if can? :manage, cohort
            %td= best_in_place cohort, :teacher, :type => :input
          - else
            %td= cohort.teacher
          - if can? :manage, cohort
            %td= link_to cohort.subject, cohort
          - else
            %td= cohort.start_date
          - if current_user.cohort_id == cohort.id
            %td.center= link_to cohort.subject, cohort
          - else
            %td= cohort.subject
          - if can? :manage, cohort
            %td.center= link_to "Delete", cohort, :confirm => 'Are you sure?', :method => :delete, :onSubmit => "window.location.href=window.location.href"
          - else
            %td Edit

/ .row
/   .col-sm-12.col-lg-12
/     %h4
/       %strong 
/     %table.display
/       %thead
/         %tr
/           %th Subject
/           %th Teacher
/           %th Start_date
/           %th End_date
/           %th Delete
/       %tbody
/       - @location.cohorts.each do |cohort|
/         %tr.odd
/           - if can? :manage, cohort
/             %td= best_in_place cohort, :subject, :type => :input
/           - else
/             %td= cohort.subject
/           - if can? :manage, cohort
/             %td= best_in_place cohort, :teacher, :type => :input
/           - else
/             %td= cohort.teacher
/           - if can? :manage, cohort
/             %td= best_in_place cohort, :start_date, :type => :input
/           - else
/             %td= cohort.start_date
/           - if current_user.cohort_id == cohort.id
/             %td.center= link_to cohort.subject, cohort
/           - else
/             %td= cohort.subject
/           - if can? :manage, cohort
/             %td.center= link_to "Delete", cohort, :remote => true, :confirm => 'Are you sure?', :method => :delete, :onSubmit => "window.location.href=window.location.href"
/           - else
/             %td Edit

/ .row
/   .col-sm-12.col-lg-12
/     %h4
/       %strong 
/     %table.display
/       %thead
/         %tr
/           %th Subject
/           %th Teacher
/           %th Start_date
/           %th End_date
/           %th Delete
/       %tbody
/       - @location.cohorts.each do |cohort|
/         %tr.odd
/           - if can? :manage, cohort
/             %td= best_in_place cohort, :subject, :type => :input
/           - else
/             %td= cohort.subject
/           - if can? :manage, cohort
/             %td= best_in_place cohort, :teacher, :type => :input
/           - else
/             %td= cohort.teacher
/           - if can? :manage, cohort
/             %td= best_in_place cohort, :start_date, :type => :input
/           - else
/             %td= cohort.start_date
/           %td.center= link_to cohort.subject, cohort
/           - if can? :manage, cohort
/             %td.center= link_to "Delete", cohort, :remote => true, :confirm => 'Are you sure?', :method => :delete
/           - else
/             %td Edit


    

app/views/locations/create.js.erb
// $(":input:not(input[type=submit])").val("");
// $("#locations_list").html("<%= escape_javascript( render(:partial => "locations") ) %>");

app/views/locations/destroy.js.erb
// $("#locations_list").html("<%= escape_javascript( render(:partial => "locations") ) %>");

app/views/locations/edit.js.erb
// $("#location_form").html("<%= escape_javascript( render(:partial => "form") ) %>");

app/views/locations/index.html.haml
%h4 Iron Yard School Locations

/ = link_to "Go to a list of all Cohorts", cohorts_path

#locations_list= render :partial => "locations"
#location_form= render :partial => "form"

app/views/locations/show.html.haml
%h4 All Cohorts in #{@location.city}

/ #locations_list= render :partial => "locationstwo"
/ #location_form= render :partial => "formtwo"

.row
  .col-sm-12.col-lg-12
    %h4
      %strong 
    %table.display
      %thead
        %tr
          %th Subject
          %th View
          %th Teacher
          %th Start_date
          %th Delete
      %tbody
      - @location.cohorts.each do |cohort|
        %tr.odd
          - if can? :manage, cohort
            %td= best_in_place cohort, :subject, :type => :input
          - else
            %td= cohort.subject

          %td= link_to cohort.subject, cohort

          - if can? :manage, cohort
            %td= best_in_place cohort, :teacher, :type => :input
          - else
            %td= cohort.teacher

          - if can? :manage, cohort
            %td= best_in_place cohort, :start_date, :type => :input
          - else
            %td= cohort.start_date

          - if can? :manage, cohort
            %td.center= link_to "Delete", cohort, :confirm => 'Are you sure?', :method => :delete, :onSubmit => "window.location.href=window.location.href"
          - else
            %td

%br

= form_for Cohort.new do |cohort|
  = cohort.hidden_field :location_id, value: @location.id
  = cohort.hidden_field :start_date
  = cohort.hidden_field :end_date
  = cohort.submit "Hello Admin, Add a New Row and Create a New Course Inline", :method => "POST", :onSubmit => "window.location.href=window.location.href"

%br
%br
%br
%br
%br
%br
%br
%br
%br
%br

/ = link_to "Add a new cohort", new_cohort_path(location_id: @location.id)

app/views/locations/show.js.erb
// $(":input:not(input[type=submit])").val("");
// $("#locations_list").html("<%= escape_javascript( render(:partial => "locations") ) %>");

// $("#locations_list").html("<%= escape_javascript( render(:partial => "locations") ) %>");
// $("#location_form").html("<%= escape_javascript( render(:partial => "form") ) %>");
// $("#locations_list").html("<%= escape_javascript( render(:partial => "locations") ) %>");

app/views/locations/update.js.erb
// $("#locations_list").html("<%= escape_javascript( render(:partial => "locations") ) %>");